server {
    listen 80;
    server_name _;

    gzip_static on;

    location /querybuilder/query/ {
        proxy_pass http://backend:8000/query/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /querybuilder/ {
        alias /usr/share/nginx/html/querybuilder/;
        try_files $uri $uri/ /querybuilder/index.html;
    }

    location = / {
        return 301 /querybuilder/;
    }
}
